// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoHFB1rwx1ODZ14TwAb_4z6bRit2bnL_k',
    appId: '1:979406213261:web:9d6d2b64d6892ed6a952c4',
    messagingSenderId: '979406213261',
    projectId: 'fixcars-b7787',
    authDomain: 'fixcars-b7787.firebaseapp.com',
    storageBucket: 'fixcars-b7787.firebasestorage.app',
    measurementId: 'G-RJKCX6TW8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_5kaHfV3aFWS5mJtWDuJ44NTo_9oJllY',
    appId: '1:979406213261:android:d67e4ff2cda41e8fa952c4',
    messagingSenderId: '979406213261',
    projectId: 'fixcars-b7787',
    storageBucket: 'fixcars-b7787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0j3saOcPFEGB0F0kWz4PepVFu-N0DqAc',
    appId: '1:979406213261:ios:133b18cc93c6e7e4a952c4',
    messagingSenderId: '979406213261',
    projectId: 'fixcars-b7787',
    storageBucket: 'fixcars-b7787.firebasestorage.app',
    iosBundleId: 'com.example.fixcars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0j3saOcPFEGB0F0kWz4PepVFu-N0DqAc',
    appId: '1:979406213261:ios:133b18cc93c6e7e4a952c4',
    messagingSenderId: '979406213261',
    projectId: 'fixcars-b7787',
    storageBucket: 'fixcars-b7787.firebasestorage.app',
    iosBundleId: 'com.example.fixcars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoHFB1rwx1ODZ14TwAb_4z6bRit2bnL_k',
    appId: '1:979406213261:web:4011b5b29732fa93a952c4',
    messagingSenderId: '979406213261',
    projectId: 'fixcars-b7787',
    authDomain: 'fixcars-b7787.firebaseapp.com',
    storageBucket: 'fixcars-b7787.firebasestorage.app',
    measurementId: 'G-X969VTN46L',
  );
}
